# Generated by Django 3.1 on 2022-06-17 14:09

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Заголовок')),
                ('key', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='key')),
                ('type', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Тип')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kit_of_values.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
                'ordering': ('-pk', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kit_of_values.value')),
                ('value', models.FileField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('name',),
            },
            bases=('kit_of_values.value',),
        ),
        migrations.CreateModel(
            name='ImageValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kit_of_values.value')),
                ('value', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('name',),
            },
            bases=('kit_of_values.value',),
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kit_of_values.value')),
                ('value', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'ordering': ('name',),
            },
            bases=('kit_of_values.value',),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='kit_of_values.group', verbose_name='Группа')),
                ('values', models.ManyToManyField(blank=True, related_name='kits', to='kit_of_values.Value', verbose_name='values')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
                'ordering': ('name',),
            },
        ),
    ]
