# Generated by Django 3.1 on 2022-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagevalue',
            name='alt',
            field=models.SlugField(default='', max_length=150, verbose_name='alt'),
        ),
    ]
