# Generated by Django 3.1 on 2022-06-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kit_of_values.value')),
                ('value', models.SlugField(max_length=150, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Slug',
                'verbose_name_plural': 'Slugs',
                'ordering': ('name',),
            },
            bases=('kit_of_values.value',),
        ),
    ]
