# Generated by Django 3.1 on 2022-06-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0004_imagevalue_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kit_of_values.value')),
                ('value', models.CharField(max_length=254, verbose_name='CharField')),
            ],
            options={
                'verbose_name': 'Char',
                'verbose_name_plural': 'Chars',
                'ordering': ('name',),
            },
            bases=('kit_of_values.value',),
        ),
    ]
