# Generated by Django 3.1 on 2022-06-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0006_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('group', 'name'), 'verbose_name': 'Набор', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('group', '-pk'), 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
    ]
