# Generated by Django 3.1 on 2022-06-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0007_auto_20220625_1810'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='kit_values',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_values', to='kit_of_values.kit', verbose_name='Набор ролей'),
        ),
    ]
