# Generated by Django 3.1 on 2022-06-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
        ('kit_of_values', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='html_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='case_pages_html', to='show.template', verbose_name='html_template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casepage',
            name='kit_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='case_page_templates', to='kit_of_values.kit', verbose_name='Набор Шаблонов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casepage',
            name='kit_values',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='case_page_values', to='kit_of_values.kit', verbose_name='Набор Значений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casespage',
            name='html_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cases_pages_html', to='show.template', verbose_name='html_template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casespage',
            name='kit_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cases_page_templates', to='kit_of_values.kit', verbose_name='Набор Шаблонов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casespage',
            name='kit_values',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cases_page_values', to='kit_of_values.kit', verbose_name='Набор Значений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampage',
            name='html_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_pages_html', to='show.template', verbose_name='html_template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampage',
            name='kit_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_page_templates', to='kit_of_values.kit', verbose_name='Набор Шаблонов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampage',
            name='kit_values',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_page_values', to='kit_of_values.kit', verbose_name='Набор Значений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeropage',
            name='html_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_pages_html', to='show.template', verbose_name='html_template'),
        ),
        migrations.AddField(
            model_name='zeropage',
            name='kit_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_page_templates', to='kit_of_values.kit', verbose_name='Набор Шаблонов'),
        ),
        migrations.AddField(
            model_name='zeropage',
            name='kit_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zero_page_values', to='kit_of_values.kit', verbose_name='Набор Значений'),
        ),
    ]
