# Generated by Django 3.1 on 2022-06-24 08:03

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('kit_of_values', '0006_tag'),
        ('pages', '0002_auto_20220623_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='color_bg',
            field=models.CharField(blank=True, max_length=9, verbose_name='Цвет Фона'),
        ),
        migrations.AddField(
            model_name='casepage',
            name='color_nuance',
            field=models.CharField(blank=True, max_length=9, verbose_name='Цвет Фона'),
        ),
        migrations.AddField(
            model_name='casepage',
            name='color_text',
            field=models.CharField(blank=True, max_length=9, verbose_name='Цвет Фона'),
        ),
        migrations.AddField(
            model_name='casepage',
            name='logo',
            field=models.FileField(blank=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='casepage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='case_pages', to='kit_of_values.Tag', verbose_name='Теги'),
        ),
    ]
