# Generated by Django 3.1 on 2022-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220624_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='casepage',
            name='color_nuance',
            field=models.CharField(blank=True, max_length=9, verbose_name='Цвет Нюанса'),
        ),
        migrations.AlterField(
            model_name='casepage',
            name='color_text',
            field=models.CharField(blank=True, max_length=9, verbose_name='Цвет Текста'),
        ),
    ]
