# Generated by Django 3.1 on 2022-06-25 15:10

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220624_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='banner',
            field=models.FileField(blank=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Банер'),
        ),
    ]
