# Generated by Django 3.1 on 2022-06-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_casepage_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepage',
            name='tim',
        ),
    ]
