# Generated by Django 3.1 on 2022-06-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kit_of_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_of_values', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_global_values', to='kit_of_values.kit', verbose_name='Набор Значений')),
            ],
            options={
                'verbose_name': 'DemoGlobal',
                'verbose_name_plural': 'DemoGlobal',
            },
        ),
    ]
