# Generated by Django 3.1 on 2022-06-14 18:29

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Свободные значение',
                'verbose_name_plural': 'Свободные значения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('basevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.basevalue')),
                ('image', models.FileField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('name',),
            },
            bases=('sample_values.basevalue',),
        ),
        migrations.CreateModel(
            name='ImageValue',
            fields=[
                ('basevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.basevalue')),
                ('image', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('name',),
            },
            bases=('sample_values.basevalue',),
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('basevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.basevalue')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'ordering': ('name',),
            },
            bases=('sample_values.basevalue',),
        ),
    ]
