# Generated by Django 3.1 on 2022-06-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('basevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.basevalue')),
                ('kay', models.CharField(db_index=True, max_length=64, verbose_name='key')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
                'ordering': ('name', 'kay'),
            },
            bases=('sample_values.basevalue',),
        ),
        migrations.CreateModel(
            name='KitOfValues',
            fields=[
                ('keyvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.keyvalue')),
                ('value', models.ManyToManyField(related_name='kit_of_values', to='sample_values.KeyValue', verbose_name='value')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
                'ordering': ('name',),
            },
            bases=('sample_values.keyvalue',),
        ),
        migrations.CreateModel(
            name='KeyAndValue',
            fields=[
                ('keyvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.keyvalue')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_and_value', to='sample_values.basevalue', verbose_name='value')),
            ],
            options={
                'verbose_name': 'Пара Ключ Значение',
                'verbose_name_plural': 'Пары Ключей и Значений',
                'ordering': ('name',),
            },
            bases=('sample_values.keyvalue',),
        ),
        migrations.CreateModel(
            name='KeyAndManyValue',
            fields=[
                ('keyvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample_values.keyvalue')),
                ('values', models.ManyToManyField(related_name='key_and_many_values', to='sample_values.BaseValue', verbose_name='values')),
            ],
            options={
                'verbose_name': 'Пара Ключ и Списка Значении',
                'verbose_name_plural': 'Пары Ключей и Списков Значений',
                'ordering': ('name',),
            },
            bases=('sample_values.keyvalue',),
        ),
    ]
