# Generated by Django 3.1 on 2022-06-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_values_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Заголовок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='sample_values_v2.group', verbose_name='Группа')),
                ('value', models.ManyToManyField(related_name='kits', to='sample_values_v2.Value', verbose_name='values')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
                'ordering': ('name',),
            },
        ),
    ]
