# Generated by Django 3.1 on 2022-06-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_values_v2', '0002_auto_20220615_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='value',
        ),
    ]
