# Generated by Django 3.1 on 2022-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_values_v2', '0003_remove_kit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='values',
            field=models.ManyToManyField(related_name='kits', to='sample_values_v2.Value', verbose_name='values'),
        ),
    ]
