# Generated by Django 3.1 on 2022-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0002_auto_20220623_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('header_menu', 'Header menu'), ('footer_menu', 'Footer menu'), ('header_menu_burger', 'Header menu burger'), ('footer_menu_burger', 'Footer menu burger')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
