from .base_value import BaseValueAdmin
from .text_value import TextValueAdmin
from .image_value import ImageValueAdmin
from .file_value import FileValueAdmin
from .key_value import KeyValueAdmin
from .key_and_value import KeyAndValueAdmin
from .key_and_many_values import KeyAndManyValueAdmin
from .kit_of_values import KitOfValuesAdmin
from .group import GroupAdmin
